library(dplyr)
library(tidyr)
library(readxl)
library(stringr)
library(purrr)
library(openxlsx)
library(readr)
library(lubridate)
library(survey)
library(ggplot2)
#install.packages("bayesplot")
library(bayesplot)
library("rstan")
#install.packages("bridgesampling")
library(bridgesampling)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
library("loo")
#install.packages("lmtest")
library(lmtest)
#install.packages("gee")
library(gee)
#install.packages("margins")
library(margins)
#install.packages("brms")
library(zoo)
library(brms)

